### ISSUE TITLE
[Bug-Candidate]: pre-commit does not work as documented

### ISSUE THREAD

**Issue by olexiyb** [crytic/slither#2549]
### Describe the issue:

I have added in my .pre-commit-config.yaml
```
   - repo: https://github.com/crytic/slither
      rev: 0.10.4
      hooks:
        - id: slither
 ```
 And I get 
 pre-commit/repoc36zuhi6/.pre-commit-hooks.yaml is not a file
 
 For some reason tag version is missing [.pre-commit-hooks.yaml](https://github.com/crytic/slither/blob/master/.pre-commit-hooks.yaml) file

### Code example to reproduce the issue:

NA

### Version:

0.10.4

**Comment by dbast** [comment]
yep. there was no release after the PR merge yet... till then the hook can be used via e.g.

```
- repo: https://github.com/crytic/slither
  # latest commit sha1 on master ... using just "master" as rev breaks hook caching
  rev: 16fd330723aca93dc3342dee77340e4b344dc732
  hooks:
    - id: slither
```
